[project]
name = "yubal-api"
version = "0.2.0"
dependencies = [
  "fastapi>=0.127.1",
  "pydantic-settings>=2.12.0",
  "uvicorn[standard]>=0.40.0",
  "yubal",
]

[build-system]
requires = ["uv_build>=0.9.23,<0.10.0"]
build-backend = "uv_build"
