# yaml-language-server: $schema=https://raw.githubusercontent.com/compose-spec/compose-spec/master/schema/compose-spec.json
---
services:
  yubal:
    image: ghcr.io/guillevc/yubal:master
    container_name: yubal
    ports:
      - 8000:${YUBAL_PORT}
    environment:
      YUBAL_PORT: ${YUBAL_PORT}
      YUBAL_AUDIO_FORMAT: ${YUBAL_AUDIO_FORMAT}
      YUBAL_AUDIO_QUALITY: ${YUBAL_AUDIO_QUALITY}
      YUBAL_TZ: ${YUBAL_TZ}
    volumes:
      - ./data:/app/data
      - ./config:/app/config
    restart: unless-stopped
