# yaml-language-server: $schema=https://raw.githubusercontent.com/compose-spec/compose-spec/master/schema/compose-spec.json
---
services:
  yubal:
    image: ghcr.io/guillevc/yubal:master
    container_name: yubal
    user: 1000:1000 # run as UID:GID (run `id` to check yours)
    ports:
      - 8000:${YUBAL_PORT}
    environment:
      YUBAL_PORT: ${YUBAL_PORT}
      YUBAL_LOG_LEVEL: ${YUBAL_LOG_LEVEL}
      YUBAL_AUDIO_FORMAT: ${YUBAL_AUDIO_FORMAT}
      YUBAL_AUDIO_QUALITY: ${YUBAL_AUDIO_QUALITY}
      YUBAL_FETCH_LYRICS: ${YUBAL_FETCH_LYRICS}
      YUBAL_SCHEDULER_ENABLED: ${YUBAL_SCHEDULER_ENABLED}
      YUBAL_SCHEDULER_CRON: ${YUBAL_SCHEDULER_CRON}
      YUBAL_TZ: ${YUBAL_TZ}
    volumes:
      - ./data:/app/data
      - ./config:/app/config
    restart: unless-stopped
